name = "factory-process-app"
compatibility_date = "2026-04-04"
pages_build_output_dir = "dist"

# D1 데이터베이스 설정
[[d1_databases]]
binding = "DB" 
database_name = "factory-process-app" 
database_id = "eadd57f7-6110-4807-9e7b-9fa734b78cb2" 

# R2 파일 저장소 설정
[[r2_buckets]]
binding = "R2"
bucket_name = "factory-attachments"
